name: Update Experience in README

on:
  schedule:
    - cron: "0 0 1 * *" # Runs on the 1st of every month
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Calculate experience and update README
        run: |
          FROM_DATE="2022-10-01"
          TODAY=$(date '+%Y-%m-%d')

          # English experience
          EXPERIENCE=$(python3 <<EOF
          from datetime import datetime
          from dateutil.relativedelta import relativedelta
          start = datetime.strptime("$FROM_DATE", "%Y-%m-%d")
          now = datetime.strptime("$TODAY", "%Y-%m-%d")
          diff = relativedelta(now, start)
          output = []
          if diff.years > 0:
              output.append(f"{diff.years} year{'s' if diff.years > 1 else ''}")
          if diff.months > 0:
              output.append(f"{diff.months} month{'s' if diff.months > 1 else ''}")
          print(", ".join(output) + " of experience")
          EOF
          )


          # Japanese experience
          EXPERIENCE_JA=$(python3 <<EOF
          from datetime import datetime
          from dateutil.relativedelta import relativedelta
          start = datetime.strptime("$FROM_DATE", "%Y-%m-%d")
          now = datetime.strptime("$TODAY", "%Y-%m-%d")
          diff = relativedelta(now, start)
          output = []
          if diff.years > 0:
              output.append(f"{diff.years}年")
          if diff.months > 0:
              output.append(f"{diff.months}ヶ月")
          print("、".join(output) + "の経験")
          EOF
          )

          # Replace inline tags using Perl
          perl -i -pe "s/<!--START_EXPERIENCE-->.*?<!--END_EXPERIENCE-->/<!--START_EXPERIENCE-->$EXPERIENCE<!--END_EXPERIENCE-->/g" README.md
          perl -i -pe "s/<!--START_EXPERIENCE_JA-->.*?<!--END_EXPERIENCE_JA-->/<!--START_EXPERIENCE_JA-->$EXPERIENCE_JA<!--END_EXPERIENCE_JA-->/g" README.md

      - name: Commit changes
        run: |
          git config user.name "prasadvamer"
          git config user.email "prasadkrishnakptp@gmail.com"
          git add README.md
          git commit -m "Update experience in README"
          git push
